/// Mirrors of the server's SneekPeek pick-lists and field caps.
///
/// GENERATED from `whatsevr_django_server/core/constants.py` — the server
/// rejects any value outside these lists with a 422, so a drift here ships a
/// form the user cannot submit. Regenerate rather than hand-edit whenever
/// `core/constants.py` changes.
library;

/// Server: `SNEEKPEEK_MIN_AGE_YEARS`. Under-18 is rejected with a 422, so the
/// date picker should make it unselectable rather than validate afterwards.
const int kSneekpeekMinAgeYears = 18;

/// Server: `SNEEKPEEK_MEDIA_MAX`. `add-candidate-media` answers 409 past this.
const int kSneekpeekMediaMax = 9;

// Field length caps. Mirror these as `maxLength` on the matching input.
const int kSneekpeekMaxName = 60;
const int kSneekpeekMaxHeadline = 60;

/// The "About" intro. Server column is `description`.
const int kSneekpeekMaxAbout = 240;
const int kSneekpeekMaxBio = 1000;
const int kSneekpeekMaxOccupation = 60;
const int kSneekpeekMaxCity = 80;
const int kSneekpeekMaxState = 80;

/// Server: `SNEEKPEEK_LANGUAGES` (40 entries, order preserved).
const List<String> kSneekpeekLanguages = <String>[
  'English',
  'Hindi',
  'Bengali',
  'Telugu',
  'Marathi',
  'Tamil',
  'Urdu',
  'Gujarati',
  'Kannada',
  'Malayalam',
  'Punjabi',
  'Odia',
  'Assamese',
  'Maithili',
  'Sanskrit',
  'Nepali',
  'Sinhala',
  'Spanish',
  'Portuguese',
  'French',
  'German',
  'Italian',
  'Dutch',
  'Russian',
  'Ukrainian',
  'Polish',
  'Turkish',
  'Arabic',
  'Persian',
  'Hebrew',
  'Mandarin',
  'Cantonese',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Filipino',
  'Swahili',
];

class SneekpeekRelationshipStatus {
  const SneekpeekRelationshipStatus({required this.value, required this.label});

  final String value;
  final String label;
}

/// Server: `SNEEKPEEK_RELATIONSHIP_STATUSES`.
///
/// There is deliberately no "prefer not to say" entry — a blank value IS that
/// answer, and the server stores it as NULL.
const List<SneekpeekRelationshipStatus> kSneekpeekRelationshipStatuses =
    <SneekpeekRelationshipStatus>[
  SneekpeekRelationshipStatus(value: 'single', label: 'Single'),
  SneekpeekRelationshipStatus(value: 'in_relationship', label: 'In a relationship'),
  SneekpeekRelationshipStatus(value: 'married', label: 'Married'),
  SneekpeekRelationshipStatus(value: 'complicated', label: 'It\'s complicated'),
];

class SneekpeekCountry {
  const SneekpeekCountry({required this.code, required this.name});

  /// ISO 3166-1 alpha-2. This is what the write endpoint expects — never the
  /// display name.
  final String code;
  final String name;
}

/// Server: `SNEEKPEEK_COUNTRIES` (197 entries).
const List<SneekpeekCountry> kSneekpeekCountries = <SneekpeekCountry>[
  SneekpeekCountry(code: 'AF', name: 'Afghanistan'),
  SneekpeekCountry(code: 'AL', name: 'Albania'),
  SneekpeekCountry(code: 'DZ', name: 'Algeria'),
  SneekpeekCountry(code: 'AD', name: 'Andorra'),
  SneekpeekCountry(code: 'AO', name: 'Angola'),
  SneekpeekCountry(code: 'AG', name: 'Antigua and Barbuda'),
  SneekpeekCountry(code: 'AR', name: 'Argentina'),
  SneekpeekCountry(code: 'AM', name: 'Armenia'),
  SneekpeekCountry(code: 'AU', name: 'Australia'),
  SneekpeekCountry(code: 'AT', name: 'Austria'),
  SneekpeekCountry(code: 'AZ', name: 'Azerbaijan'),
  SneekpeekCountry(code: 'BS', name: 'Bahamas'),
  SneekpeekCountry(code: 'BH', name: 'Bahrain'),
  SneekpeekCountry(code: 'BD', name: 'Bangladesh'),
  SneekpeekCountry(code: 'BB', name: 'Barbados'),
  SneekpeekCountry(code: 'BY', name: 'Belarus'),
  SneekpeekCountry(code: 'BE', name: 'Belgium'),
  SneekpeekCountry(code: 'BZ', name: 'Belize'),
  SneekpeekCountry(code: 'BJ', name: 'Benin'),
  SneekpeekCountry(code: 'BT', name: 'Bhutan'),
  SneekpeekCountry(code: 'BO', name: 'Bolivia'),
  SneekpeekCountry(code: 'BA', name: 'Bosnia and Herzegovina'),
  SneekpeekCountry(code: 'BW', name: 'Botswana'),
  SneekpeekCountry(code: 'BR', name: 'Brazil'),
  SneekpeekCountry(code: 'BN', name: 'Brunei'),
  SneekpeekCountry(code: 'BG', name: 'Bulgaria'),
  SneekpeekCountry(code: 'BF', name: 'Burkina Faso'),
  SneekpeekCountry(code: 'BI', name: 'Burundi'),
  SneekpeekCountry(code: 'KH', name: 'Cambodia'),
  SneekpeekCountry(code: 'CM', name: 'Cameroon'),
  SneekpeekCountry(code: 'CA', name: 'Canada'),
  SneekpeekCountry(code: 'CV', name: 'Cape Verde'),
  SneekpeekCountry(code: 'CF', name: 'Central African Republic'),
  SneekpeekCountry(code: 'TD', name: 'Chad'),
  SneekpeekCountry(code: 'CL', name: 'Chile'),
  SneekpeekCountry(code: 'CN', name: 'China'),
  SneekpeekCountry(code: 'CO', name: 'Colombia'),
  SneekpeekCountry(code: 'KM', name: 'Comoros'),
  SneekpeekCountry(code: 'CG', name: 'Congo'),
  SneekpeekCountry(code: 'CD', name: 'Congo (DRC)'),
  SneekpeekCountry(code: 'CR', name: 'Costa Rica'),
  SneekpeekCountry(code: 'CI', name: 'Côte d\'Ivoire'),
  SneekpeekCountry(code: 'HR', name: 'Croatia'),
  SneekpeekCountry(code: 'CU', name: 'Cuba'),
  SneekpeekCountry(code: 'CY', name: 'Cyprus'),
  SneekpeekCountry(code: 'CZ', name: 'Czechia'),
  SneekpeekCountry(code: 'DK', name: 'Denmark'),
  SneekpeekCountry(code: 'DJ', name: 'Djibouti'),
  SneekpeekCountry(code: 'DM', name: 'Dominica'),
  SneekpeekCountry(code: 'DO', name: 'Dominican Republic'),
  SneekpeekCountry(code: 'EC', name: 'Ecuador'),
  SneekpeekCountry(code: 'EG', name: 'Egypt'),
  SneekpeekCountry(code: 'SV', name: 'El Salvador'),
  SneekpeekCountry(code: 'GQ', name: 'Equatorial Guinea'),
  SneekpeekCountry(code: 'ER', name: 'Eritrea'),
  SneekpeekCountry(code: 'EE', name: 'Estonia'),
  SneekpeekCountry(code: 'SZ', name: 'Eswatini'),
  SneekpeekCountry(code: 'ET', name: 'Ethiopia'),
  SneekpeekCountry(code: 'FJ', name: 'Fiji'),
  SneekpeekCountry(code: 'FI', name: 'Finland'),
  SneekpeekCountry(code: 'FR', name: 'France'),
  SneekpeekCountry(code: 'GA', name: 'Gabon'),
  SneekpeekCountry(code: 'GM', name: 'Gambia'),
  SneekpeekCountry(code: 'GE', name: 'Georgia'),
  SneekpeekCountry(code: 'DE', name: 'Germany'),
  SneekpeekCountry(code: 'GH', name: 'Ghana'),
  SneekpeekCountry(code: 'GR', name: 'Greece'),
  SneekpeekCountry(code: 'GD', name: 'Grenada'),
  SneekpeekCountry(code: 'GT', name: 'Guatemala'),
  SneekpeekCountry(code: 'GN', name: 'Guinea'),
  SneekpeekCountry(code: 'GW', name: 'Guinea-Bissau'),
  SneekpeekCountry(code: 'GY', name: 'Guyana'),
  SneekpeekCountry(code: 'HT', name: 'Haiti'),
  SneekpeekCountry(code: 'HN', name: 'Honduras'),
  SneekpeekCountry(code: 'HK', name: 'Hong Kong'),
  SneekpeekCountry(code: 'HU', name: 'Hungary'),
  SneekpeekCountry(code: 'IS', name: 'Iceland'),
  SneekpeekCountry(code: 'IN', name: 'India'),
  SneekpeekCountry(code: 'ID', name: 'Indonesia'),
  SneekpeekCountry(code: 'IR', name: 'Iran'),
  SneekpeekCountry(code: 'IQ', name: 'Iraq'),
  SneekpeekCountry(code: 'IE', name: 'Ireland'),
  SneekpeekCountry(code: 'IL', name: 'Israel'),
  SneekpeekCountry(code: 'IT', name: 'Italy'),
  SneekpeekCountry(code: 'JM', name: 'Jamaica'),
  SneekpeekCountry(code: 'JP', name: 'Japan'),
  SneekpeekCountry(code: 'JO', name: 'Jordan'),
  SneekpeekCountry(code: 'KZ', name: 'Kazakhstan'),
  SneekpeekCountry(code: 'KE', name: 'Kenya'),
  SneekpeekCountry(code: 'KI', name: 'Kiribati'),
  SneekpeekCountry(code: 'KW', name: 'Kuwait'),
  SneekpeekCountry(code: 'KG', name: 'Kyrgyzstan'),
  SneekpeekCountry(code: 'LA', name: 'Laos'),
  SneekpeekCountry(code: 'LV', name: 'Latvia'),
  SneekpeekCountry(code: 'LB', name: 'Lebanon'),
  SneekpeekCountry(code: 'LS', name: 'Lesotho'),
  SneekpeekCountry(code: 'LR', name: 'Liberia'),
  SneekpeekCountry(code: 'LY', name: 'Libya'),
  SneekpeekCountry(code: 'LI', name: 'Liechtenstein'),
  SneekpeekCountry(code: 'LT', name: 'Lithuania'),
  SneekpeekCountry(code: 'LU', name: 'Luxembourg'),
  SneekpeekCountry(code: 'MO', name: 'Macao'),
  SneekpeekCountry(code: 'MG', name: 'Madagascar'),
  SneekpeekCountry(code: 'MW', name: 'Malawi'),
  SneekpeekCountry(code: 'MY', name: 'Malaysia'),
  SneekpeekCountry(code: 'MV', name: 'Maldives'),
  SneekpeekCountry(code: 'ML', name: 'Mali'),
  SneekpeekCountry(code: 'MT', name: 'Malta'),
  SneekpeekCountry(code: 'MH', name: 'Marshall Islands'),
  SneekpeekCountry(code: 'MR', name: 'Mauritania'),
  SneekpeekCountry(code: 'MU', name: 'Mauritius'),
  SneekpeekCountry(code: 'MX', name: 'Mexico'),
  SneekpeekCountry(code: 'FM', name: 'Micronesia'),
  SneekpeekCountry(code: 'MD', name: 'Moldova'),
  SneekpeekCountry(code: 'MC', name: 'Monaco'),
  SneekpeekCountry(code: 'MN', name: 'Mongolia'),
  SneekpeekCountry(code: 'ME', name: 'Montenegro'),
  SneekpeekCountry(code: 'MA', name: 'Morocco'),
  SneekpeekCountry(code: 'MZ', name: 'Mozambique'),
  SneekpeekCountry(code: 'MM', name: 'Myanmar'),
  SneekpeekCountry(code: 'NA', name: 'Namibia'),
  SneekpeekCountry(code: 'NR', name: 'Nauru'),
  SneekpeekCountry(code: 'NP', name: 'Nepal'),
  SneekpeekCountry(code: 'NL', name: 'Netherlands'),
  SneekpeekCountry(code: 'NZ', name: 'New Zealand'),
  SneekpeekCountry(code: 'NI', name: 'Nicaragua'),
  SneekpeekCountry(code: 'NE', name: 'Niger'),
  SneekpeekCountry(code: 'NG', name: 'Nigeria'),
  SneekpeekCountry(code: 'KP', name: 'North Korea'),
  SneekpeekCountry(code: 'MK', name: 'North Macedonia'),
  SneekpeekCountry(code: 'NO', name: 'Norway'),
  SneekpeekCountry(code: 'OM', name: 'Oman'),
  SneekpeekCountry(code: 'PK', name: 'Pakistan'),
  SneekpeekCountry(code: 'PW', name: 'Palau'),
  SneekpeekCountry(code: 'PS', name: 'Palestine'),
  SneekpeekCountry(code: 'PA', name: 'Panama'),
  SneekpeekCountry(code: 'PG', name: 'Papua New Guinea'),
  SneekpeekCountry(code: 'PY', name: 'Paraguay'),
  SneekpeekCountry(code: 'PE', name: 'Peru'),
  SneekpeekCountry(code: 'PH', name: 'Philippines'),
  SneekpeekCountry(code: 'PL', name: 'Poland'),
  SneekpeekCountry(code: 'PT', name: 'Portugal'),
  SneekpeekCountry(code: 'QA', name: 'Qatar'),
  SneekpeekCountry(code: 'RO', name: 'Romania'),
  SneekpeekCountry(code: 'RU', name: 'Russia'),
  SneekpeekCountry(code: 'RW', name: 'Rwanda'),
  SneekpeekCountry(code: 'KN', name: 'Saint Kitts and Nevis'),
  SneekpeekCountry(code: 'LC', name: 'Saint Lucia'),
  SneekpeekCountry(code: 'VC', name: 'Saint Vincent and the Grenadines'),
  SneekpeekCountry(code: 'WS', name: 'Samoa'),
  SneekpeekCountry(code: 'SM', name: 'San Marino'),
  SneekpeekCountry(code: 'ST', name: 'São Tomé and Príncipe'),
  SneekpeekCountry(code: 'SA', name: 'Saudi Arabia'),
  SneekpeekCountry(code: 'SN', name: 'Senegal'),
  SneekpeekCountry(code: 'RS', name: 'Serbia'),
  SneekpeekCountry(code: 'SC', name: 'Seychelles'),
  SneekpeekCountry(code: 'SL', name: 'Sierra Leone'),
  SneekpeekCountry(code: 'SG', name: 'Singapore'),
  SneekpeekCountry(code: 'SK', name: 'Slovakia'),
  SneekpeekCountry(code: 'SI', name: 'Slovenia'),
  SneekpeekCountry(code: 'SB', name: 'Solomon Islands'),
  SneekpeekCountry(code: 'SO', name: 'Somalia'),
  SneekpeekCountry(code: 'ZA', name: 'South Africa'),
  SneekpeekCountry(code: 'KR', name: 'South Korea'),
  SneekpeekCountry(code: 'SS', name: 'South Sudan'),
  SneekpeekCountry(code: 'ES', name: 'Spain'),
  SneekpeekCountry(code: 'LK', name: 'Sri Lanka'),
  SneekpeekCountry(code: 'SD', name: 'Sudan'),
  SneekpeekCountry(code: 'SR', name: 'Suriname'),
  SneekpeekCountry(code: 'SE', name: 'Sweden'),
  SneekpeekCountry(code: 'CH', name: 'Switzerland'),
  SneekpeekCountry(code: 'SY', name: 'Syria'),
  SneekpeekCountry(code: 'TW', name: 'Taiwan'),
  SneekpeekCountry(code: 'TJ', name: 'Tajikistan'),
  SneekpeekCountry(code: 'TZ', name: 'Tanzania'),
  SneekpeekCountry(code: 'TH', name: 'Thailand'),
  SneekpeekCountry(code: 'TL', name: 'Timor-Leste'),
  SneekpeekCountry(code: 'TG', name: 'Togo'),
  SneekpeekCountry(code: 'TO', name: 'Tonga'),
  SneekpeekCountry(code: 'TT', name: 'Trinidad and Tobago'),
  SneekpeekCountry(code: 'TN', name: 'Tunisia'),
  SneekpeekCountry(code: 'TR', name: 'Türkiye'),
  SneekpeekCountry(code: 'TM', name: 'Turkmenistan'),
  SneekpeekCountry(code: 'TV', name: 'Tuvalu'),
  SneekpeekCountry(code: 'UG', name: 'Uganda'),
  SneekpeekCountry(code: 'UA', name: 'Ukraine'),
  SneekpeekCountry(code: 'AE', name: 'United Arab Emirates'),
  SneekpeekCountry(code: 'GB', name: 'United Kingdom'),
  SneekpeekCountry(code: 'US', name: 'United States'),
  SneekpeekCountry(code: 'UY', name: 'Uruguay'),
  SneekpeekCountry(code: 'UZ', name: 'Uzbekistan'),
  SneekpeekCountry(code: 'VU', name: 'Vanuatu'),
  SneekpeekCountry(code: 'VE', name: 'Venezuela'),
  SneekpeekCountry(code: 'VN', name: 'Vietnam'),
  SneekpeekCountry(code: 'YE', name: 'Yemen'),
  SneekpeekCountry(code: 'ZM', name: 'Zambia'),
  SneekpeekCountry(code: 'ZW', name: 'Zimbabwe'),
];

/// Server: `SNEEKPEEK_IN_STATES` (36 entries: states, then
/// union territories). The web renders a cascading state picker from this
/// whenever country is `IN`; anywhere else `state` is free text.
const List<String> kSneekpeekIndiaStates = <String>[
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

/// The country whose states are enumerated above.
const String kSneekpeekCascadingStateCountry = 'IN';
